apiVersion: apps/v1
kind: Deployment
metadata:
  name: bioit-wiki
spec:
  selector:
    matchLabels:
      app: klgn-bioit-wiki
  replicas: 2
  template:
    metadata:
      labels:
        app: klgn-bioit-wiki
    spec:
      containers:
      - name: klgn-bioit-wiki
        image: geertgeeven/klgn-bioit-wiki:1.0
        ports:
        - containerPort: 8000
